name: Deploy to Production

on:
  push:
    branches:
      - main
      - access-restrictions

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      BRIDGE_HOSTNAME: ${{ secrets.BRIDGE_HOSTNAME }}
      PRODUCTION_HOSTNAME: ${{ secrets.PRODUCTION_HOSTNAME }}
      DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
      VITE_APP_TITLE: ${{ secrets.APP_TITLE }}
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      VITE_GITHUB_CALLBACK_URL: ${{ secrets.GH_CALLBACK_URL }}
      VITE_GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
      VITE_ACCESS_API_URL: ${{ secrets.ACCESS_API_URL }}
      VITE_BLE_SERVICE_UUID: ${{ secrets.BLE_SERVICE_UUID }}
      VITE_BLE_CHARACTERISTIC_UUID: ${{ secrets.BLE_CHARACTERISTIC_UUID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Build project
        run: pnpm build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host unison-bridge\n\tHostName $BRIDGE_HOSTNAME\n\tUser $DEPLOY_USERNAME\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tForwardAgent yes\n" > ~/.ssh/config
          echo -e "Host unison-production\n\tHostName $PRODUCTION_HOSTNAME\n\tUser $DEPLOY_USERNAME\n\tProxyJump unison-bridge\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tForwardAgent yes\n" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Generate .env file
        run: |
          echo "VITE_APP_TITLE=$VITE_APP_TITLE" > .env.local
          echo "VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY" >> .env.local
          echo "VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN" >> .env.local
          echo "VITE_FIREBASE_DB_URL=$VITE_FIREBASE_DB_URL" >> .env.local
          echo "VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID" >> .env.local
          echo "VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET" >> .env.local
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID" >> .env.local
          echo "VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID" >> .env.local
          echo "VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID" >> .env.local
          echo "VITE_GITHUB_CALLBACK_URL=$VITE_GITHUB_CALLBACK_URL" >> .env.local
          echo "VITE_GITHUB_CLIENT_ID=$VITE_GITHUB_CLIENT_ID" >> .env.local
          echo "VITE_ACCESS_API_URL=$VITE_ACCESS_API_URL" >> .env.local
          echo "VITE_BLE_SERVICE_UUID=$VITE_BLE_SERVICE_UUID" >> .env.local
          echo "VITE_BLE_CHARACTERISTIC_UUID=$VITE_BLE_CHARACTERISTIC_UUID" >> .env.local

      - name: Transfer files to Production
        run: |
          rsync -rvz --delete ./dist/ unison-production:/var/www/access-web/
